// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: emissary.proto

package emissaryproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerSoftware  string `protobuf:"bytes,1,opt,name=server_software,json=serverSoftware,proto3" json:"server_software,omitempty"`     // What's the server software name
	ServerVersion   string `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`        // What's the server's version
	ProtocolVersion int32  `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // What's the protocol version we're going to use
	ConnectionNonce []byte `protobuf:"bytes,4,opt,name=connection_nonce,json=connectionNonce,proto3" json:"connection_nonce,omitempty"`  // What's the server's requested nonce
}

func (x *ServerConnect) Reset() {
	*x = ServerConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emissary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConnect) ProtoMessage() {}

func (x *ServerConnect) ProtoReflect() protoreflect.Message {
	mi := &file_emissary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConnect.ProtoReflect.Descriptor instead.
func (*ServerConnect) Descriptor() ([]byte, []int) {
	return file_emissary_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConnect) GetServerSoftware() string {
	if x != nil {
		return x.ServerSoftware
	}
	return ""
}

func (x *ServerConnect) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *ServerConnect) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ServerConnect) GetConnectionNonce() []byte {
	if x != nil {
		return x.ConnectionNonce
	}
	return nil
}

var File_emissary_proto protoreflect.FileDescriptor

var file_emissary_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x61, 0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb5, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x6f, 0x66, 0x74,
	0x77, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x65, 0x6d, 0x69, 0x73,
	0x73, 0x61, 0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_emissary_proto_rawDescOnce sync.Once
	file_emissary_proto_rawDescData = file_emissary_proto_rawDesc
)

func file_emissary_proto_rawDescGZIP() []byte {
	file_emissary_proto_rawDescOnce.Do(func() {
		file_emissary_proto_rawDescData = protoimpl.X.CompressGZIP(file_emissary_proto_rawDescData)
	})
	return file_emissary_proto_rawDescData
}

var file_emissary_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_emissary_proto_goTypes = []interface{}{
	(*ServerConnect)(nil), // 0: emissaryproto.ServerConnect
}
var file_emissary_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_emissary_proto_init() }
func file_emissary_proto_init() {
	if File_emissary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_emissary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emissary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_emissary_proto_goTypes,
		DependencyIndexes: file_emissary_proto_depIdxs,
		MessageInfos:      file_emissary_proto_msgTypes,
	}.Build()
	File_emissary_proto = out.File
	file_emissary_proto_rawDesc = nil
	file_emissary_proto_goTypes = nil
	file_emissary_proto_depIdxs = nil
}
